repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^apps/distributed-frontend/frontend/

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        exclude: ^(uv\.lock|apps/distributed-frontend/frontend/package-lock\.json)$

  - repo: local
    hooks:
      - id: format
        name: Format Python
        entry: make
        args: [format]
        language: system
        types: [python]
        pass_filenames: false
      - id: lint
        name: Lint Python
        entry: make
        args: [lint]
        language: system
        types: [python]
        pass_filenames: false
